services:
  dex:
    container_name: dex
    image: dexidp/dex:latest
    restart: unless-stopped
    ports:
      - 5556:5556
    volumes:
      - ./dex.yaml:/etc/dex/config.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.yaml"]
  postgres:
    container_name: postgres
    image: postgis/postgis:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: shuttr
      POSTGRES_USER: shuttr
      POSTGRES_PASSWORD: shuttr
      POSTGRES_PORT: 5432
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  minio:
    container_name: minio
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/shuttr && /usr/bin/minio server --console-address ":9001" --quiet /data'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: shuttr
      MINIO_ROOT_PASSWORD: shuttrshuttr
      MINIO_DEFAULT_BUCKETS: shuttr:public
      MINIO_SCHEME: http
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio:/data

volumes:
  postgres: {}
  minio: {}
