services:
  dex:
    container_name: dex-acc
    image: dexidp/dex:latest
    restart: unless-stopped
    ports:
      - 5556:5556
    volumes:
      - ./dex.yaml:/etc/dex/config.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.yaml"]
  postgres:
    container_name: postgres-acc
    image: postgis/postgis:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: shuttr
      POSTGRES_USER: shuttr
      POSTGRES_PASSWORD: shuttr
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "shuttr", "-U", "shuttr"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  adminer:
    container_name: adminer-acc
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  minio:
    container_name: minio-acc
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/shuttr && /usr/bin/minio server --console-address ":9001" --quiet /data'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: shuttr
      MINIO_ROOT_PASSWORD: shuttrshuttr
      MINIO_DEFAULT_BUCKETS: shuttr:public
      MINIO_SCHEME: http
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio:/data
  shuttr:
    container_name: shuttr-acc
    build:
      dockerfile: Dockerfile
    depends_on:
      - dex
      - postgres
      - minio
    ports:
      - 80:80
    environment:
      NUXT_SESSION_PASSWORD: SHUTTRSHUTTRSHUTTRSHUTTRSHUTTRSHUTTR
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: shuttr
      DATABASE_PASSWORD: shuttr
      DATABASE_DB: shuttr
      DATABASE_SSL: false
      NUXT_STORAGE_TYPE: s3
      NUXT_STORAGE_THUMB_CACHE_MAX: 30
      NUXT_STORAGE_S3_ACCESS_KEY: shuttr
      NUXT_STORAGE_S3_SECRET_KEY: shuttrshuttr
      NUXT_STORAGE_S3_BUCKET: shuttr
      NUXT_STORAGE_S3_ENDPOINT: http://minio:9000
      NUXT_STORAGE_S3_REGION: us-west-1

volumes:
  postgres: {}
  minio: {}
