services:
  dex:
    container_name: dex
    image: dexidp/dex:latest
    restart: unless-stopped
    ports:
      - 5556:5556
    volumes:
      - ./dex.yaml:/etc/dex/config.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.yaml"]
  postgres:
    container_name: postgres
    image: postgis/postgis:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: shuttr
      POSTGRES_USER: shuttr
      POSTGRES_PASSWORD: shuttr
      POSTGRES_PORT: 5432
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres: {}
